"""
HTML formatter for the final report.
Converts Markdown to clean, styled HTML and merges research findings.
"""
from typing import Dict, Any
import markdown

REPORT_STYLE = """
<style>
    body { font-family: 'Inter', sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 1000px; margin: 0 auto; padding: 40px; background: #f9fafb; }
    .container { background: white; padding: 50px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }
    h1 { color: #111827; font-size: 2.5em; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; margin-bottom: 30px; }
    h2 { color: #1f2937; font-size: 1.8em; margin-top: 40px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
    h3 { color: #374151; font-size: 1.4em; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.9em; }
    th { background: #f3f4f6; color: #4b5563; font-weight: 600; text-align: left; padding: 12px; border: 1px solid #e5e7eb; }
    td { padding: 12px; border: 1px solid #e5e7eb; vertical-align: top; }
    tr:nth-child(even) { background: #f9fafb; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 0.8em; font-weight: 500; }
    .badge-red { background: #fee2e2; color: #991b1b; }
    .badge-green { background: #dcfce7; color: #166534; }
    .research-section { background: #fff7ed; border-left: 4px solid #f97316; padding: 20px; margin: 20px 0; border-radius: 0 8px 8px 0; }
</style>
"""

class ReportFormatter:
    def format(self, company_name: str, summary_md: str, research: Dict[str, Any]) -> str:
        """
        Converts summary and research data into a final HTML report.
        """
        # Convert Markdown to HTML
        summary_html = markdown.markdown(summary_md, extensions=['tables', 'fenced_code'])
        
        # Format Research Section
        research_html = self._format_research(research)
        
        # Assemble Final Page
        final_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{company_name} - Analysis Report</title>
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
            {REPORT_STYLE}
        </head>
        <body>
            <div class="container">
                <h1>Investment Analysis Report: {company_name}</h1>
                
                <div class="research-section">
                    <h2>🔍 Adverse Findings Research (External Search)</h2>
                    {research_html}
                </div>
                
                <div class="summary-section">
                    {summary_html}
                </div>
                
                <hr>
                <p style="text-align: center; color: #6b7280; font-size: 0.8em;">
                    Generated by AI Python Platform | Confidential - Investor Grade
                </p>
            </div>
        </body>
        </html>
        """
        return final_html

    def _format_research(self, research: Dict[str, Any]) -> str:
        """Helper to format the research JSON into HTML snippets."""
        if "error" in research:
            return f"<p>Research Error: {research['error']}</p>"
        
        exec_sum = research.get("executive_summary", {})
        risk = research.get("risk_assessment", {})
        
        html = f"""
        <p><strong>Risk Level:</strong> <span class="badge {'badge-red' if exec_sum.get('adverse_flag') else 'badge-green'}">
            {exec_sum.get('risk_level', 'Unknown')}
        </span></p>
        <p><strong>Key Findings:</strong> {exec_sum.get('key_findings', 'None')}</p>
        <p><strong>Risk Factors Identified:</strong></p>
        <ul>
            {''.join(f"<li>{r}</li>" for r in risk.get('risk_factors', []))}
        </ul>
        """
        return html

report_formatter = ReportFormatter()
