version: '3.8'
services:
  node-backend:
    platform: linux/amd64
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    # Node backend usually needs MongoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
