name: Trigger auto deployment for aca-node-backend-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-node-backend-prod-AutoDeployTrigger-b4931227-0bd1-4abe-a0a5-c2eb11995032.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACANODEBACKENDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACANODEBACKENDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACANODEBACKENDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: drhpacr.azurecr.io
          registryUsername: ${{ secrets.ACANODEBACKENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACANODEBACKENDPROD_REGISTRY_PASSWORD }}
          containerAppName: aca-node-backend-prod
          resourceGroup: DRHP-summarizer
          imageToBuild: drhpacr.azurecr.io/aca-node-backend-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


