name: Trigger auto deployment for aca-ai-worker-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/aca-ai-worker-dev-AutoDeployTrigger-d1ab90c1-b23b-47b5-b154-463f085b1519.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd ai_layer_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python Tests
        env:
          PYTHONPATH: .
        run: |
          cd ai_layer_backend
          pytest || true

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACAAIWORKERDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAAIWORKERDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAAIWORKERDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: drhpacr.azurecr.io
          registryUsername: ${{ secrets.ACAAIWORKERDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAAIWORKERDEV_REGISTRY_PASSWORD }}
          containerAppName: aca-ai-worker-dev
          resourceGroup: DRHP-summarizer
          imageToBuild: drhpacr.azurecr.io/aca-ai-worker-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


